package de.bsnsoft.megarepo.app.license;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import de.bsnsoft.megarepo.database.repository.AuditLogJpaRepository;
import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.KeyFactory;
import java.security.PublicKey;
import java.security.Signature;
import java.security.spec.X509EncodedKeySpec;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Base64;
import java.util.Optional;

@Service
public class LicenseService {

    private static final Logger log = LoggerFactory.getLogger(LicenseService.class);

    private static final int FREE_TIER_USER_LIMIT = 50;

    // @formatter:off
    // RSA 2048-bit public key for license signature verification
    // Generated by tools/license-signer/generate-keys.sh
    // Private key is at BSNSoft Solutions GmbH — NEVER committed to source
    private static final String PUBLIC_KEY_PEM =
            "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsRCb87/DXGJ6uiLFyKw7"
          + "0EnE6icXX2J0JBbw22ImyEvvpfY1jTsvhtgcULxWA3t/M2wCo15Oav4UHob5dz/w"
          + "Eg6M1HD75eHw2j8uqR1lTSukeIFXvgqH+v3k+IETbz9hW+h2Y6R1YskMF5v8oUj3"
          + "cUOch7FbbzH4O8VKpjmH4o6JsXV/jyvhmEp3mp2nK46bsSVrIVhfM0nBrGGxJn8q"
          + "dRto8PN8wjm5noDiRkv/XUQAhbKasK+QBfEXiUpdbwn2+1pU5Fx64lr+5ie9oeeD"
          + "tx0cBxdlpBUOy8Js5H7/icnhGfL8MN4F5FY7vPNe6tkwCySFSFoqlv9tI+9Ynep4"
          + "2wIDAQAB";
    // @formatter:on

    private final AuditLogJpaRepository auditLogJpaRepository;
    private final ObjectMapper objectMapper;
    private final Path licensePath;

    private volatile LicenseInfo cachedLicense;

    public LicenseService(
            AuditLogJpaRepository auditLogJpaRepository,
            ObjectMapper objectMapper,
            @Value("${megarepo.license.path:./megarepo.license}") String licensePath) {
        this.auditLogJpaRepository = auditLogJpaRepository;
        this.objectMapper = objectMapper;
        this.licensePath = Path.of(licensePath);
    }

    @PostConstruct
    void loadLicense() {
        if (Files.exists(licensePath)) {
            try {
                var content = Files.readAllBytes(licensePath);
                cachedLicense = parseLicense(content);
                if (cachedLicense.valid()) {
                    log.info("License loaded: licensed to {}", cachedLicense.company());
                } else {
                    log.warn("License file found but signature is invalid");
                }
            } catch (IOException e) {
                log.warn("Failed to read license file at {}: {}", licensePath, e.getMessage());
            }
        } else {
            log.info("No license file found at {} - running as Community Edition", licensePath);
        }
    }

    public Optional<LicenseInfo> getLicenseInfo() {
        return Optional.ofNullable(cachedLicense).filter(LicenseInfo::valid);
    }

    public boolean isLicensed() {
        return cachedLicense != null && cachedLicense.valid();
    }

    public LicenseInfo uploadLicense(byte[] content) throws IOException {
        var license = parseLicense(content);
        if (!license.valid()) {
            throw new IllegalArgumentException("Invalid license: signature verification failed");
        }
        Files.createDirectories(licensePath.getParent());
        Files.write(licensePath, content);
        cachedLicense = license;
        log.info("License uploaded and saved: licensed to {}", license.company());
        return license;
    }

    public void removeLicense() throws IOException {
        Files.deleteIfExists(licensePath);
        cachedLicense = null;
        log.info("License removed");
    }

    public int getActiveUserCount() {
        var thirtyDaysAgo = Instant.now().minus(30, ChronoUnit.DAYS);
        return auditLogJpaRepository.countDistinctActiveUsers(thirtyDaysAgo);
    }

    public boolean requiresLicense() {
        return getActiveUserCount() > FREE_TIER_USER_LIMIT && !isLicensed();
    }

    LicenseInfo parseLicense(byte[] content) {
        try {
            var root = objectMapper.readTree(content);
            var company = getText(root, "company");
            var email = getText(root, "email");
            var issuedAt = getText(root, "issuedAt");
            var licenseId = getText(root, "licenseId");
            var signature = getText(root, "signature");

            if (company == null || email == null || issuedAt == null || licenseId == null || signature == null) {
                return new LicenseInfo(company, email, issuedAt, null, licenseId, false);
            }

            var validUntil = getText(root, "validUntil");
            var data = company + "|" + email + "|" + issuedAt + "|" + validUntil + "|" + licenseId;
            var valid = verifySignature(data, signature, loadPublicKey());
            return new LicenseInfo(company, email, issuedAt, validUntil, licenseId, valid);
        } catch (Exception e) {
            log.warn("Failed to parse license: {}", e.getMessage());
            return new LicenseInfo(null, null, null, null, null, false);
        }
    }

    private static String getText(JsonNode node, String field) {
        var child = node.get(field);
        return child != null && child.isTextual() ? child.asText() : null;
    }

    private boolean verifySignature(String data, String signatureBase64, PublicKey publicKey) {
        try {
            var sig = Signature.getInstance("SHA256withRSA");
            sig.initVerify(publicKey);
            sig.update(data.getBytes(StandardCharsets.UTF_8));
            return sig.verify(Base64.getDecoder().decode(signatureBase64));
        } catch (Exception e) {
            log.warn("Signature verification failed: {}", e.getMessage());
            return false;
        }
    }

    private PublicKey loadPublicKey() throws Exception {
        var keyBytes = Base64.getDecoder().decode(PUBLIC_KEY_PEM);
        var keySpec = new X509EncodedKeySpec(keyBytes);
        return KeyFactory.getInstance("RSA").generatePublic(keySpec);
    }
}
